server:
  port: 5011
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic

logging:
  level:
    com.example: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

spring:
  rabbitmq:
    host: 'localhost'
    password: password
    port: 5672
    username: user

rabbitmq:
  exchange:
    producer: test.event
  route:
    test: event.test.route
  queue:
    test: event.test.queue

app:
  gc-two:
    url: http://localhost:5003
    name: gc-two
  gc-one:
    url: http://localhost:5002
    name: gc-one
